feat: add slack action and normalize inputs

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,27 +1,73 @@
 name: "API and migrations status"
 description: "Check migrations and health"
 inputs:
-  url:  # id of input
-    description: 'URL Website'
+  URL:  # id of input
+    description: "URL Website"
+  CHANNEL_ID: 
+    description: "Channel ID"
+  SLACK_BOT_TOKEN:
+    description: "Slack bot token"
 outputs:
-  code:
+  CODE:
     description: "Status Code"
     value: ${{ steps.status_code.outputs.status_code }}
-  migrations_check:
+  MIGRATIONS_CHECK:
     description: "Migrations Check"
     value: ${{ steps.migrations_check.outputs.migrations_check }}
 runs:
   using: "composite"
   steps:
-    - id: status_code
+    - name: API Status Code
+      id: status_code
       run: |
-        if ! code=$(curl -w 'Type: %{content_type}\nCode: %{response_code}\n' ${{ inputs.url }}/ht/ | grep -w Code | sed "s/ //g" | cut -d ":" -f 2); then echo "Failure :fire:"; fi
+        if ! code=$(curl -w 'Type: %{content_type}\nCode: %{response_code}\n' ${{ inputs.URL }}/ht/ | grep -w Code | sed "s/ //g" | cut -d ":" -f 2); then echo "Failure :fire:"; fi
         echo "status_code=$(if [ "$code" = "200" ]; then echo "Completed :white_check_mark:"; else echo "Failure :fire:"; fi)" >> $GITHUB_OUTPUT
       shell: bash
 
-    - id: migrations_check
+    - name: API Migrations Check
+      id: migrations_check
       run: | 
-        if ! check=$(curl -v GET ${{ inputs.url }}/ht/\?format\=json | grep -w MigrationsHealthCheck | cut -d \" -f 4); then echo "Failure :fire:"; fi
+        if ! check=$(curl -v GET ${{ inputs.URL }}/ht/\?format\=json | grep -w MigrationsHealthCheck | cut -d \" -f 4); then echo "Failure :fire:"; fi
         echo "migrations_check=$(if [ "$check" = "working" ]; then echo "Completed :white_check_mark:"; else echo "Failure :fire:"; fi)" >> $GITHUB_OUTPUT
       shell: bash
+
+    - name: Notify to Slack channel
+        uses: slackapi/slack-github-action@v1.23.0
+        with:
+          channel-id: ${{ inputs.CHANNEL_ID}}
+          payload: |
+            {
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "New deployment ready :rocket:"
+                  }
+                },
+                {
+                  "type": "section",
+                  "fields": [
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Status:*\n ${{ steps.foo.outputs.code }}"
+                    },
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Environment:*\n ${{ github.ref_name }}"
+                    },
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Migrations:*\n ${{ steps.foo.outputs.migrations_check }}"
+                    },
+                    {
+                      "type": "mrkdwn",
+                      "text": "*Changes:*\n ${{ github.event.head_commit.message }}"
+                    }
+                  ]
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN}}
 
