chore: avoid fail command

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -13,15 +13,15 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - id: status_code
+      run: |
+        if ! code=$(curl -w 'Type: %{content_type}\nCode: %{response_code}\n' ${{ inputs.url }}/ht/ | grep -w Code | sed "s/ //g" | cut -d ":" -f 2); then echo "Failure :fire:"; fi
+        echo "status_code=$(if [ "$code" = "200" ]; then echo "Completed :white_check_mark:"; else echo "Failure :fire:"; fi)" >> $GITHUB_OUTPUT
+      shell: bash
+
     - id: migrations_check
       run: | 
-        check=$(curl -v GET ${{ inputs.url }}/ht/\?format\=json | grep -w MigrationsHealthCheck | cut -d \" -f 4)
+        if ! check=$(curl -v GET ${{ inputs.url }}/ht/\?format\=json | grep -w MigrationsHealthCheck | cut -d \" -f 4); then echo "Failure :fire:"; fi
         echo "migrations_check=$(if [ "$check" = "working" ]; then echo "Completed :white_check_mark:"; else echo "Failure :fire:"; fi)" >> $GITHUB_OUTPUT
       shell: bash
 
-
-    - id: status_code
-      run: |
-        code=$(curl -w 'Type: %{content_type}\nCode: %{response_code}\n' ${{ inputs.url }}/ht/ | grep -w Code | sed "s/ //g" | cut -d ":" -f 2)
-        echo "status_code=$(if [ "$code" = "200" ]; then echo "Completed :white_check_mark:"; else echo "Failure :fire:"; fi)" >> $GITHUB_OUTPUT
-      shell: bash
